//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IDashboardApiClient {

    /**
     * Get dashboard metrics
     * @return Successful Response
     */
    getMetrics(): Promise<DashboardMetricsSchema>;

    /**
     * Get full combined dashboard dataset
     * @return Successful Response
     */
    getFullData(): Promise<FullDashboardDataSchema>;

    /**
     * Get entity DAG dependency graph for Cytoscape
     * @return Successful Response
     */
    getDagGraph(): Promise<any>;

    /**
     * List all issues
     * @param status (optional) Filter by status (open, in-progress, blocked, done)
     * @param type (optional) Filter by type (feat, bug, debt, task, docs)
     * @param priority (optional) Filter by priority (critical, high, medium, low)
     * @param milestone (optional) Filter by milestone slug
     * @return Successful Response
     */
    listIssues(status?: string | null | undefined, type?: string | null | undefined, priority?: string | null | undefined, milestone?: string | null | undefined): Promise<IssueSchema[]>;

    /**
     * Get issue details
     * @return Successful Response
     */
    getIssue(issue_id: string): Promise<IssueSchema>;

    /**
     * List all milestones
     * @return Successful Response
     */
    listMilestones(): Promise<MilestoneSchema[]>;

    /**
     * List all risks
     * @return Successful Response
     */
    listRisks(): Promise<RiskSchema[]>;

    /**
     * List all spikes
     * @return Successful Response
     */
    listSpikes(): Promise<SpikeSchema[]>;

    /**
     * List all session logs
     * @return Successful Response
     */
    listSessions(): Promise<SessionSchema[]>;

    /**
     * List all ADR decisions
     * @return Successful Response
     */
    listDecisions(): Promise<DecisionSchema[]>;

    /**
     * List all Knowledge Base articles
     * @param type (optional) Filter by category type
     * @param tag (optional) Filter by tag
     * @return Successful Response
     */
    listArticles(type?: string | null | undefined, tag?: string | null | undefined): Promise<KBArticleSchema[]>;

    /**
     * Search Knowledge Base and entities
     * @param q (optional) Search query string
     * @param tag (optional) Filter by tag
     * @param type (optional) Filter by entity type (kb, issue, decision, session)
     * @return Successful Response
     */
    searchKb(q?: string | undefined, tag?: string | null | undefined, type?: string | null | undefined): Promise<SearchResponse>;

    /**
     * Get Knowledge Base cross-link graph
     * @return Successful Response
     */
    getKbGraph(): Promise<KBGraphSchema>;

    /**
     * Get single Knowledge Base article
     * @return Successful Response
     */
    getArticle(slug: string): Promise<KBArticleSchema>;

    /**
     * Stream live repository changes via Server-Sent Events (SSE)
     * @return Successful Response
     */
    streamEvents(): Promise<any>;
}

export class DashboardApiClient implements IDashboardApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get dashboard metrics
     * @return Successful Response
     */
    getMetrics(): Promise<DashboardMetricsSchema> {
        let url_ = this.baseUrl + "/api/metrics";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetMetrics(_response);
        });
    }

    protected processGetMetrics(response: Response): Promise<DashboardMetricsSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DashboardMetricsSchema;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DashboardMetricsSchema>(null as any);
    }

    /**
     * Get full combined dashboard dataset
     * @return Successful Response
     */
    getFullData(): Promise<FullDashboardDataSchema> {
        let url_ = this.baseUrl + "/api/data";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFullData(_response);
        });
    }

    protected processGetFullData(response: Response): Promise<FullDashboardDataSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as FullDashboardDataSchema;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FullDashboardDataSchema>(null as any);
    }

    /**
     * Get entity DAG dependency graph for Cytoscape
     * @return Successful Response
     */
    getDagGraph(): Promise<any> {
        let url_ = this.baseUrl + "/api/graph";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetDagGraph(_response);
        });
    }

    protected processGetDagGraph(response: Response): Promise<any> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<any>(null as any);
    }

    /**
     * List all issues
     * @param status (optional) Filter by status (open, in-progress, blocked, done)
     * @param type (optional) Filter by type (feat, bug, debt, task, docs)
     * @param priority (optional) Filter by priority (critical, high, medium, low)
     * @param milestone (optional) Filter by milestone slug
     * @return Successful Response
     */
    listIssues(status?: string | null | undefined, type?: string | null | undefined, priority?: string | null | undefined, milestone?: string | null | undefined): Promise<IssueSchema[]> {
        let url_ = this.baseUrl + "/api/entities/issues?";
        if (status !== undefined && status !== null)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (type !== undefined && type !== null)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (priority !== undefined && priority !== null)
            url_ += "priority=" + encodeURIComponent("" + priority) + "&";
        if (milestone !== undefined && milestone !== null)
            url_ += "milestone=" + encodeURIComponent("" + milestone) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListIssues(_response);
        });
    }

    protected processListIssues(response: Response): Promise<IssueSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IssueSchema[];
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IssueSchema[]>(null as any);
    }

    /**
     * Get issue details
     * @return Successful Response
     */
    getIssue(issue_id: string): Promise<IssueSchema> {
        let url_ = this.baseUrl + "/api/entities/issues/{issue_id}";
        if (issue_id === undefined || issue_id === null)
            throw new globalThis.Error("The parameter 'issue_id' must be defined.");
        url_ = url_.replace("{issue_id}", encodeURIComponent("" + issue_id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetIssue(_response);
        });
    }

    protected processGetIssue(response: Response): Promise<IssueSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IssueSchema;
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IssueSchema>(null as any);
    }

    /**
     * List all milestones
     * @return Successful Response
     */
    listMilestones(): Promise<MilestoneSchema[]> {
        let url_ = this.baseUrl + "/api/entities/milestones";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListMilestones(_response);
        });
    }

    protected processListMilestones(response: Response): Promise<MilestoneSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MilestoneSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MilestoneSchema[]>(null as any);
    }

    /**
     * List all risks
     * @return Successful Response
     */
    listRisks(): Promise<RiskSchema[]> {
        let url_ = this.baseUrl + "/api/entities/risks";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListRisks(_response);
        });
    }

    protected processListRisks(response: Response): Promise<RiskSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RiskSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RiskSchema[]>(null as any);
    }

    /**
     * List all spikes
     * @return Successful Response
     */
    listSpikes(): Promise<SpikeSchema[]> {
        let url_ = this.baseUrl + "/api/entities/spikes";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListSpikes(_response);
        });
    }

    protected processListSpikes(response: Response): Promise<SpikeSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SpikeSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpikeSchema[]>(null as any);
    }

    /**
     * List all session logs
     * @return Successful Response
     */
    listSessions(): Promise<SessionSchema[]> {
        let url_ = this.baseUrl + "/api/entities/sessions";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListSessions(_response);
        });
    }

    protected processListSessions(response: Response): Promise<SessionSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SessionSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SessionSchema[]>(null as any);
    }

    /**
     * List all ADR decisions
     * @return Successful Response
     */
    listDecisions(): Promise<DecisionSchema[]> {
        let url_ = this.baseUrl + "/api/entities/decisions";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListDecisions(_response);
        });
    }

    protected processListDecisions(response: Response): Promise<DecisionSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DecisionSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DecisionSchema[]>(null as any);
    }

    /**
     * List all Knowledge Base articles
     * @param type (optional) Filter by category type
     * @param tag (optional) Filter by tag
     * @return Successful Response
     */
    listArticles(type?: string | null | undefined, tag?: string | null | undefined): Promise<KBArticleSchema[]> {
        let url_ = this.baseUrl + "/api/kb?";
        if (type !== undefined && type !== null)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (tag !== undefined && tag !== null)
            url_ += "tag=" + encodeURIComponent("" + tag) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListArticles(_response);
        });
    }

    protected processListArticles(response: Response): Promise<KBArticleSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as KBArticleSchema[];
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KBArticleSchema[]>(null as any);
    }

    /**
     * Search Knowledge Base and entities
     * @param q (optional) Search query string
     * @param tag (optional) Filter by tag
     * @param type (optional) Filter by entity type (kb, issue, decision, session)
     * @return Successful Response
     */
    searchKb(q?: string | undefined, tag?: string | null | undefined, type?: string | null | undefined): Promise<SearchResponse> {
        let url_ = this.baseUrl + "/api/kb/search?";
        if (q === null)
            throw new globalThis.Error("The parameter 'q' cannot be null.");
        else if (q !== undefined)
            url_ += "q=" + encodeURIComponent("" + q) + "&";
        if (tag !== undefined && tag !== null)
            url_ += "tag=" + encodeURIComponent("" + tag) + "&";
        if (type !== undefined && type !== null)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSearchKb(_response);
        });
    }

    protected processSearchKb(response: Response): Promise<SearchResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SearchResponse>(null as any);
    }

    /**
     * Get Knowledge Base cross-link graph
     * @return Successful Response
     */
    getKbGraph(): Promise<KBGraphSchema> {
        let url_ = this.baseUrl + "/api/kb/graph";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetKbGraph(_response);
        });
    }

    protected processGetKbGraph(response: Response): Promise<KBGraphSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as KBGraphSchema;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KBGraphSchema>(null as any);
    }

    /**
     * Get single Knowledge Base article
     * @return Successful Response
     */
    getArticle(slug: string): Promise<KBArticleSchema> {
        let url_ = this.baseUrl + "/api/kb/{slug}";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetArticle(_response);
        });
    }

    protected processGetArticle(response: Response): Promise<KBArticleSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as KBArticleSchema;
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KBArticleSchema>(null as any);
    }

    /**
     * Stream live repository changes via Server-Sent Events (SSE)
     * @return Successful Response
     */
    streamEvents(): Promise<any> {
        let url_ = this.baseUrl + "/api/events";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamEvents(_response);
        });
    }

    protected processStreamEvents(response: Response): Promise<any> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<any>(null as any);
    }
}

/** Aggregated project metrics. */
export interface DashboardMetricsSchema {
    total_issues: number;
    open_issues: number;
    in_progress_issues: number;
    blocked_issues: number;
    done_issues: number;
    completion_pct: number;
    bug_debt_ratio: number;
    active_risks: number;
    active_milestones: number;
    total_kb_articles: number;
    total_decisions: number;
    total_sessions: number;
    by_status: StatusBreakdown;
    by_type: TypeBreakdown;
    by_priority: PriorityBreakdown;
    scan_timestamp: string;
    protocol_version: string;
}

/** Schema for an ADR entry in .along/DECISIONS.md. */
export interface DecisionSchema {
    /** Decision identifier, e.g. ADR-001 */
    id: string;
    /** Decision slug */
    slug: string | undefined;
    /** Sequential ADR number */
    number: number | undefined;
    /** Decision title */
    title: string;
    /** Date recorded YYYY-MM-DD */
    date: string | undefined;
    /** ADR status (Accepted, Superseded, etc.) */
    status: string;
    /** Context and problem description */
    context: string | undefined;
    /** Decision made */
    decision: string | undefined;
    /** Consequences and trade-offs */
    consequences: string | undefined;
    /** ADR identifier that supersedes this */
    superseded_by: string | undefined;
    /** Relative path to ADR file */
    file_path: string | undefined;
    /** Full raw markdown of the entry */
    raw_markdown: string | undefined;
}

/** Complete dataset for dashboard SPA. */
export interface FullDashboardDataSchema {
    repo_name: string;
    metrics: DashboardMetricsSchema;
    issues: IssueSchema[];
    milestones: MilestoneSchema[];
    risks: RiskSchema[];
    spikes: SpikeSchema[];
    sessions: SessionSchema[];
    decisions: DecisionSchema[];
    kb_articles: KBArticleSchema[];
    graph: any;
    context_text: string;
    issues_board_text: string;
}

export interface HTTPValidationError {
    detail: ValidationError[];
}

/** Schema for .along/ISSUES/<type>--<slug>.md. */
export interface IssueSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: string | undefined;
    /** Markdown body content */
    body: string | undefined;
    /** Relative file path in repository */
    file_path: string | undefined;
    /** Issue type */
    type: IssueSchemaType;
    /** Current lifecycle status */
    status: IssueSchemaStatus;
    /** Priority level */
    priority: IssueSchemaPriority;
    /** Creation date YYYY-MM-DD */
    created: string | undefined;
    /** Last update date YYYY-MM-DD */
    updated: string | undefined;
    /** Completion date YYYY-MM-DD */
    completed: string | undefined;
    /** Agent or author that worked on the issue */
    agent: string | undefined;
    /** Array of topical tags */
    tags: string[];
    /** Milestone slug this issue belongs to */
    milestone: string | undefined;
    /** List of blocking entity keys */
    blocked_by: string[];
    /** List of related entity keys */
    related: string[];
    /** Parent epic/entity key */
    parent: string | undefined;
    /** Canonical entity key that supersedes this issue */
    superseded_by: string | undefined;
    /** Canonical entity key this issue duplicates */
    duplicate_of: string | undefined;
}

/** Schema for Knowledge Base article in .along/KB/ or docs/. */
export interface KBArticleSchema {
    /** Unique article ID, e.g. kb--architecture or docs--setup */
    id: string;
    /** Article slug or filename */
    slug: string;
    /** Article title */
    title: string;
    /** Article topic category */
    type: KBArticleSchemaType;
    /** Creation date YYYY-MM-DD */
    created: string | undefined;
    /** Last update date YYYY-MM-DD */
    updated: string | undefined;
    /** List of topic tags */
    tags: string[];
    /** Relative path in repository */
    file_path: string;
    /** Markdown body */
    body: string;
    /** Extracted Markdown headings */
    headings: string[];
    /** Outgoing wiki or entity links */
    outgoing_links: string[];
    /** Incoming links referencing this article */
    incoming_links: string[];
}

export interface KBGraphEdge {
    source: string;
    target: string;
    type: string;
    label: string | undefined;
}

export interface KBGraphNode {
    id: string;
    label: string;
    type: string;
    category: string;
    tags: string[];
}

/** Bidirectional graph of Knowledge Base articles and related entities. */
export interface KBGraphSchema {
    nodes: KBGraphNode[];
    edges: KBGraphEdge[];
}

/** Schema for .along/MILESTONES/<slug>.md. */
export interface MilestoneSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: string | undefined;
    /** Markdown body content */
    body: string | undefined;
    /** Relative file path in repository */
    file_path: string | undefined;
    /** Milestone status */
    status: MilestoneSchemaStatus;
    /** Target due date YYYY-MM-DD */
    due_date: string | undefined;
    /** Creation date YYYY-MM-DD */
    created: string | undefined;
    /** Target issue slugs or keys */
    target_issues: string[];
    /** Completion percentage */
    progress_pct: number;
}

export interface PriorityBreakdown {
    critical: number;
    high: number;
    medium: number;
    low: number;
}

/** Schema for .along/RISKS/<slug>.md. */
export interface RiskSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: string | undefined;
    /** Markdown body content */
    body: string | undefined;
    /** Relative file path in repository */
    file_path: string | undefined;
    /** Risk severity level */
    severity: RiskSchemaSeverity;
    /** Risk status */
    status: RiskSchemaStatus;
    /** Owner (agent or user) */
    owner: string | undefined;
    /** Mitigation strategy summary */
    mitigation: string | undefined;
    /** Creation date YYYY-MM-DD */
    created: string | undefined;
    /** Update date YYYY-MM-DD */
    updated: string | undefined;
}

export interface SearchResponse {
    query: string;
    total: number;
    results: SearchResultItem[];
}

export interface SearchResultItem {
    id: string;
    title: string;
    type: string;
    snippet: string;
    file_path: string;
    score: number;
    tags: string[];
}

/** Schema for .along/SESSIONS/<YYYY>/<YYYY-MM-DD>--<slug>.md. */
export interface SessionSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: string | undefined;
    /** Markdown body content */
    body: string | undefined;
    /** Relative file path in repository */
    file_path: string | undefined;
    /** Session date YYYY-MM-DD */
    date: string;
    /** Agent model/tool name */
    agent: string | undefined;
    /** Git branch name */
    branch: string | undefined;
    /** Git commit hash */
    commit: string | undefined;
    /** Summary of work completed */
    summary: string | undefined;
    /** Associated milestone */
    milestone: string | undefined;
    /** Advanced issue keys */
    issues_advanced: string[];
    /** Completed issue keys */
    issues_completed: string[];
    /** Recorded ADR numbers/titles */
    decisions: string[];
    /** Logged risk keys */
    risks_logged: string[];
    /** Conducted spike keys */
    spikes_conducted: string[];
}

/** Schema for .along/SPIKES/<slug>.md. */
export interface SpikeSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: string | undefined;
    /** Markdown body content */
    body: string | undefined;
    /** Relative file path in repository */
    file_path: string | undefined;
    /** Spike state */
    status: SpikeSchemaStatus;
    /** Spike hypothesis statement */
    hypothesis: string | undefined;
    /** Spike outcome and conclusion */
    outcome: string | undefined;
    /** Linked ADR in DECISIONS.md */
    resulting_adr: string | undefined;
    /** Creation date YYYY-MM-DD */
    created: string | undefined;
}

export interface StatusBreakdown {
    open: number;
    in_progress: number;
    blocked: number;
    done: number;
    superseded: number;
    cancelled: number;
    duplicate: number;
}

export interface TypeBreakdown {
    feat: number;
    bug: number;
    debt: number;
    task: number;
    docs: number;
}

export interface ValidationError {
    loc: Loc[];
    msg: string;
    type: string;
    input: any;
    ctx: any;
}

export type IssueSchemaType = "feat" | "bug" | "debt" | "task" | "docs";

export type IssueSchemaStatus = "open" | "in-progress" | "blocked" | "done" | "superseded" | "cancelled" | "duplicate";

export type IssueSchemaPriority = "critical" | "high" | "medium" | "low";

export type KBArticleSchemaType = "topic" | "architecture" | "domain-model" | "setup-workflow" | "index" | "doc";

export type MilestoneSchemaStatus = "open" | "in-progress" | "completed";

export type RiskSchemaSeverity = "critical" | "high" | "medium" | "low";

export type RiskSchemaStatus = "active" | "mitigated" | "resolved";

export type SpikeSchemaStatus = "hypothesis" | "evaluating" | "concluded";

export interface Loc {

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}